# Use the official Docker Hub Postgres image
# https://hub.docker.com/_/postgres
FROM postgres:latest

# Set environment variables
ENV POSTGRES_USER badjuju
ENV POSTGRES_PASSWORD mypassword
ENV POSTGRES_DB mydatabase